wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.16.2
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706100178.000136
    t:
      1:
      - 5
      - 6
      - 8
      - 53
      - 54
      - 55
      2:
      - 5
      - 6
      - 8
      - 53
      - 54
      - 55
      3:
      - 23
      4: 3.11.3
      5: 0.16.2
      8:
      - 3
      - 5
      13: windows-amd64
